### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by matthaias** [topa/gignx#12]
### Testing

[jasmine](http://pivotal.github.io/jasmine/) framework is used to run the tests. It is installed via NPM. At the moment there is a grunt task to run all tests in the <code>spec</code> folder. This grunt task uses the [grunt-jasmine-node](https://github.com/jasmine-contrib/grunt-jasmine-node) plugin. The files must end with <code>spec.js</code>

**Comment by topa** [comment]
There is a lib included called jsUnit. I'll give it a try.
