### ISSUE TITLE
Project Structure

### ISSUE THREAD

**Issue by matthaias** [topa/gignx#9]
## Grunt tasks
- [x] install 
- [x] test
- [ ] watch-test
- [ ] reload-gnome-shell

**Comment by topa** [comment]
## IDE-Settings (PHPStorm)

### JavaScript
- activate support for JavaScript 1.8 (you'll see the FireFox 3.0+-Logo (which seems to be correct as gjs seems to be an spidermonkey implementation)
  ![js_version_support](https://f.cloud.github.com/assets/1116484/1321841/a8673dd8-33f3-11e3-9f42-0905ab185100.jpg)

### Libraries
- remove all environments 
- and add gnome-shell js-libraries loacted in <code>/usr/share/gnome-shell/js</code> to get auto-completion support
- also download/activate node.js-plugin (if not already done) for grunt.js development
  ![js_libraries](https://f.cloud.github.com/assets/1116484/1321853/f2428772-33f4-11e3-9c7e-ef55af9647a2.jpg)
- manage your scopes
  ![js_libraries_scopes](https://f.cloud.github.com/assets/1116484/1321862/c3449914-33f5-11e3-84e2-45ed12b2258b.jpg)

### Code Quality
- activate jshint and remove browser environment
- add node.js (for grunt-task development)
  ![jshint_environment_settings](https://f.cloud.github.com/assets/1116484/1321848/1e173f06-33f4-11e3-99b3-90c78bd2ace0.jpg)

@matthaias please configure your ide

**Comment by matthaias** [comment]
### Tests

Tests are stored in the <code>spec</code> folder. [jasmine](https://github.com/mhevery/jasmine-node) framework is used to run the tests. The test files must end with spec.js.

There is a task to run the tests: <code>grunt test</code>
